(()=>{'use strict';
const $=id=>document.getElementById(id),CFG=window.FUEL_TRACKER_CONFIG||{},KEY='fuelTracker.data.v2',OLD='fuelTracker.entries.v1',OPS='fuelTracker.pending.v1';
const money=new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}),num=(n,d=1)=>new Intl.NumberFormat('en-AU',{minimumFractionDigits:d,maximumFractionDigits:d}).format(n),parse=(s,f)=>{try{return JSON.parse(s)||f}catch{return f}},uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,9),esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),today=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d-o*60000).toISOString().slice(0,10)};
let data=parse(localStorage.getItem(KEY),{version:2,vehicles:[]}),legacy=parse(localStorage.getItem(OLD),[]),activeId=null,fuelRows=[];if(!Array.isArray(data.vehicles))data={version:2,vehicles:[]};if(!Array.isArray(legacy))legacy=[];
const configured=CFG.supabaseUrl&&CFG.supabasePublishableKey&&!CFG.supabaseUrl.includes('YOUR-'),headers={'apikey':CFG.supabasePublishableKey,'Authorization':'Bearer '+CFG.supabasePublishableKey,'Content-Type':'application/json','Prefer':'return=minimal'},base=()=>CFG.supabaseUrl.replace(/\/$/,'')+'/rest/v1',active=()=>data.vehicles.find(v=>v.id===activeId),fills=v=>v&&Array.isArray(v.fills)?v.fills:[];
function cache(){localStorage.setItem(KEY,JSON.stringify(data))}function status(s,kind=''){$('sync').textContent=s;$('sync').className='sync '+kind}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1900)}
async function api(path,opt={}){const r=await fetch(base()+path,{...opt,headers:{...headers,...opt.headers}}),text=await r.text();if(!r.ok)throw Error(text||r.statusText);return text?JSON.parse(text):null}
function queue(op){const q=parse(localStorage.getItem(OPS),[]);q.push(op);localStorage.setItem(OPS,JSON.stringify(q))}async function send(op){return api(op.path,{method:op.method,body:op.body?JSON.stringify(op.body):undefined,headers:op.prefer?{'Prefer':op.prefer}:undefined})}async function mutate(op){cache();if(!configured){status('Local only','offline');return}try{await send(op);status('Synced','online')}catch(e){queue(op);status('Saved offline','offline')}}
async function flush(){const q=parse(localStorage.getItem(OPS),[]);if(!q.length)return;for(let i=0;i<q.length;i++){try{await send(q[i])}catch{localStorage.setItem(OPS,JSON.stringify(q.slice(i)));throw Error('pending')}}localStorage.removeItem(OPS)}
async function sync(){if(!configured)return status('Setup needed','offline');status('Syncing…');try{await flush();const ws=encodeURIComponent(CFG.workspace||'default');let [vs,fs]=await Promise.all([api(`/vehicles?workspace=eq.${ws}&select=id,rego,nickname&order=created_at.asc`),api(`/fill_ups?workspace=eq.${ws}&select=id,vehicle_id,fill_date,distance_km,litres,price_per_litre,odometer_km&order=fill_date.desc,created_at.desc`)]);if(!vs.length&&data.vehicles.length){for(const v of data.vehicles)await uploadVehicle(v);return sync()}const local=new Map(data.vehicles.map(v=>[v.id,v]));data.vehicles=vs.map(v=>({id:v.id,rego:v.rego,nickname:v.nickname||'',fills:fs.filter(f=>f.vehicle_id===v.id).map(f=>({id:f.id,date:f.fill_date,distance:+f.distance_km,litres:+f.litres,price:+f.price_per_litre,odometer:f.odometer_km==null?null:+f.odometer_km}))}));for(const v of local.values())if(!data.vehicles.some(x=>x.id===v.id)){await uploadVehicle(v);data.vehicles.push(v)}cache();picker();status('Synced','online')}catch(e){status('Offline cache','offline')}}
async function uploadVehicle(v){const ws=CFG.workspace||'default';await send({method:'POST',path:'/vehicles?on_conflict=id',body:{id:v.id,workspace:ws,rego:v.rego,nickname:v.nickname||null},prefer:'resolution=merge-duplicates,return=minimal'});if(fills(v).length)await send({method:'POST',path:'/fill_ups?on_conflict=id',body:fills(v).map(f=>({id:f.id,workspace:ws,vehicle_id:v.id,fill_date:f.date,distance_km:f.distance,litres:f.litres,price_per_litre:f.price,odometer_km:f.odometer})),prefer:'resolution=merge-duplicates,return=minimal'})}
function picker(){activeId=null;$('dashboard').classList.add('hidden');$('picker').classList.remove('hidden');$('legacy').classList.toggle('hidden',!legacy.length||data.vehicles.length);$('legacy').textContent=legacy.length+` existing fill${legacy.length===1?'':'s'} found. They will move safely into the first vehicle you add.`;$('vehicleGrid').innerHTML=data.vehicles.map(v=>`<button class="vehicle-tile" data-id="${esc(v.id)}"><span>🚙</span><strong>${esc(v.rego)}</strong><span>${esc(v.nickname||'No nickname')} · ${fills(v).length} fills</span><em>Open →</em></button>`).join('')+'<button class="vehicle-tile add-tile" data-add><strong>＋ Add vehicle</strong><span>Set up another rego</span></button>'}
$('vehicleGrid').onclick=e=>{const b=e.target.closest('button');if(b)b.dataset.add!==undefined?dialog():openVehicle(b.dataset.id)};function openVehicle(id){activeId=id;const v=active();if(!v)return picker();$('picker').classList.add('hidden');$('dashboard').classList.remove('hidden');$('vRego').textContent=v.rego;$('vName').textContent=v.nickname||'Vehicle dashboard';reset();render();scrollTo(0,0)}$('back').onclick=picker;
function dialog(v){$('dialogTitle').textContent=v?'Vehicle settings':'Add vehicle';$('editId').value=v?v.id:'';$('rego').value=v?v.rego:'';$('nickname').value=v?v.nickname:'';$('deleteVehicle').classList.toggle('hidden',!v);$('vDialog').showModal()}$('settings').onclick=()=>dialog(active());$('cancel').onclick=()=>$('vDialog').close();
$('vForm').onsubmit=async e=>{e.preventDefault();const rego=$('rego').value.trim().toUpperCase(),nickname=$('nickname').value.trim(),id=$('editId').value;if(data.vehicles.some(v=>v.rego.toUpperCase()===rego&&v.id!==id))return alert('That rego already exists.');let v;if(id){v=active();v.rego=rego;v.nickname=nickname}else{const old=data.vehicles.length?[]:legacy.map(x=>({...x,id:x.id||uid(),odometer:x.odometer??null}));v={id:uid(),rego,nickname,fills:old};data.vehicles.push(v);activeId=v.id;if(old.length){localStorage.removeItem(OLD);legacy=[]}}await mutate({method:'POST',path:'/vehicles?on_conflict=id',body:{id:v.id,workspace:CFG.workspace||'default',rego,nickname:nickname||null},prefer:'resolution=merge-duplicates,return=minimal'});if(v.fills.length)try{await uploadVehicle(v)}catch{}$('vDialog').close();openVehicle(v.id);toast(id?'Vehicle updated':'Vehicle added')};
$('deleteVehicle').onclick=async()=>{const v=active();if(v&&confirm(`Delete ${v.rego} and all its fills?`)){data.vehicles=data.vehicles.filter(x=>x.id!==v.id);await mutate({method:'DELETE',path:'/vehicles?id=eq.'+encodeURIComponent(v.id)});$('vDialog').close();picker();toast('Vehicle deleted')}};
const form=$('fillForm');function vals(){const d=+$('distance').value,l=+$('litres').value,p=+$('price').value,o=$('odo').value===''?null:+$('odo').value;return{d,l,p,o,ok:d>0&&l>0&&p>0}}function preview(){const x=vals();$('result').classList.toggle('show',x.ok);if(x.ok){$('rUse').textContent=num(x.l/x.d*100,2);$('rRate').textContent=money.format(x.l*x.p/x.d*100);$('rCost').textContent=money.format(x.l*x.p)}}['distance','litres','price'].forEach(id=>$(id).oninput=preview);function reset(){
  form.reset();
  $('date').value=today();
  $('result').classList.remove('show');
}

form.onreset=()=>setTimeout(()=>{
  $('date').value=today();
  $('result').classList.remove('show');
},0);
form.onsubmit=async e=>{e.preventDefault();const x=vals(),v=active();if(!x.ok)return form.reportValidity();const f={id:uid(),date:$('date').value,distance:x.d,litres:x.l,price:x.p,odometer:x.o};v.fills.unshift(f);await mutate({method:'POST',path:'/fill_ups',body:{id:f.id,workspace:CFG.workspace||'default',vehicle_id:v.id,fill_date:f.date,distance_km:f.distance,litres:f.litres,price_per_litre:f.price,odometer_km:f.odometer}});reset();render();toast('Fill saved')};
$('history').onclick=async e=>{const b=e.target.closest('[data-del]'),v=active();if(b&&confirm('Delete this fill?')){v.fills=v.fills.filter(x=>x.id!==b.dataset.del);await mutate({method:'DELETE',path:'/fill_ups?id=eq.'+encodeURIComponent(b.dataset.del)});render();toast('Fill deleted')}};$('clear').onclick=async()=>{const v=active();if(fills(v).length&&confirm(`Delete every fill for ${v.rego}?`)){v.fills=[];await mutate({method:'DELETE',path:'/fill_ups?vehicle_id=eq.'+encodeURIComponent(v.id)});render()}};
function render(){const fs=fills(active()),t=fs.reduce((a,x)=>({d:a.d+x.distance,l:a.l+x.litres,s:a.s+x.litres*x.price}),{d:0,l:0,s:0}),u=fs.map(x=>x.litres/x.distance*100).filter(Number.isFinite),r=u.slice(0,3),odos=fs.map(x=>x.odometer).filter(Number.isFinite),set=(id,v)=>$(id).textContent=v;set('avgUse',t.d?num(t.l/t.d*100,2):'—');set('rolling',r.length?num(r.reduce((a,b)=>a+b)/r.length,2):'—');set('best',u.length?num(Math.min(...u),2):'—');set('worst',u.length?num(Math.max(...u),2):'—');set('avgRate',t.d?money.format(t.s/t.d*100):'—');set('spend',money.format(t.s));set('avgPrice',t.l?money.format(t.s/t.l)+'/L':'—');set('avgFill',fs.length?money.format(t.s/fs.length):'—');set('totalKm',num(t.d)+' km');set('totalL',num(t.l,2)+' L');set('lastOdo',odos.length?num(Math.max(...odos))+' km':'—');set('costKm',t.d?money.format(t.s/t.d)+'/km':'—');$('history').innerHTML=fs.length?fs.map(x=>`<article class="entry"><div class="entry-top"><div><strong>${dateFmt(x.date)}</strong><div class="entry-main">${num(x.litres/x.distance*100,2)} L/100 km · ${money.format(x.litres*x.price/x.distance*100)}/100 km</div></div><button class="del" data-del="${esc(x.id)}">✕</button></div><div class="entry-details"><span>${num(x.distance)} km</span><span>${num(x.litres,2)} L</span><span>${money.format(x.price)}/L</span><span>${money.format(x.litres*x.price)} total</span>${x.odometer!=null?`<span>Odo ${num(x.odometer)} km</span>`:''}</div></article>`).join(''):'<div class="empty">No fills for this vehicle yet.</div>';lineChart('chart',fs.slice().reverse().map(x=>x.litres/x.distance*100),null,'Your trend appears after the first fill')}
function lineChart(id,a,b,empty){const cv=$(id),q=devicePixelRatio||1,w=Math.max(280,cv.getBoundingClientRect().width),h=225;cv.width=w*q;cv.height=h*q;const c=cv.getContext('2d');c.scale(q,q);if(!a.length&&!b?.length){c.fillStyle='#93a4ba';c.textAlign='center';c.fillText(empty,w/2,h/2);return}const vals=[...a,...(b||[])].filter(Number.isFinite),mn=Math.min(...vals)-1,mx=Math.max(...vals)+1,p={l:42,r:12,t:15,b:24},x=(i,n)=>p.l+(n===1?(w-p.l-p.r)/2:i*(w-p.l-p.r)/(n-1)),y=v=>p.t+(mx-v)*(h-p.t-p.b)/(mx-mn||1);c.strokeStyle='#293b54';c.fillStyle='#93a4ba';c.font='10px system-ui';c.textAlign='right';for(let i=0;i<4;i++){const yy=p.t+i*(h-p.t-p.b)/3;c.beginPath();c.moveTo(p.l,yy);c.lineTo(w-p.r,yy);c.stroke();c.fillText((mx-i*(mx-mn)/3).toFixed(1),p.l-5,yy+3)}const draw=(z,col)=>{if(!z.length)return;c.beginPath();z.forEach((v,i)=>i?c.lineTo(x(i,z.length),y(v)):c.moveTo(x(i,z.length),y(v)));c.strokeStyle=col;c.lineWidth=2.5;c.stroke()};draw(a,'#55d8a0');if(b)draw(b,'#53b7e8')}
async function loadFuel(){try{const r=await fetch('fuel_history.csv?'+Date.now());if(!r.ok)throw Error();const lines=(await r.text()).trim().split(/\r?\n/),head=lines.shift().split(',');fuelRows=lines.map(l=>{const v=l.split(',');return Object.fromEntries(head.map((h,i)=>[h,v[i]]))}).filter(x=>x.fuel&&Number.isFinite(+x.price_cents)).sort((a,b)=>new Date(a.api_time_utc)-new Date(b.api_time_utc));for(const [fuel,id] of [['Diesel','dieselPrice'],['U91','u91Price']]){const row=fuelRows.filter(x=>x.fuel===fuel).at(-1);$(id).textContent=row?num(+row.price_cents,1)+' c/L':'—'}const latest=fuelRows.at(-1);$('fuelUpdated').textContent=latest?'Last price update '+new Intl.DateTimeFormat('en-AU',{dateStyle:'medium',timeStyle:'short',timeZone:'Australia/Brisbane'}).format(new Date(latest.api_time_utc)):'No price records yet';drawFuel()}catch{$('fuelUpdated').textContent='Price history is temporarily unavailable.';drawFuel()}}
function drawFuel(){const d=fuelRows.filter(x=>x.fuel==='Diesel').map(x=>+x.price_cents),u=fuelRows.filter(x=>x.fuel==='U91').map(x=>+x.price_cents);lineChart('fuelChart',d,u,'Price history will appear after the first GitHub Action run')}function dateFmt(s){return new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(s+'T00:00:00Z'))}$('refreshFuel').onclick=loadFuel;addEventListener('resize',()=>{drawFuel();if(activeId)render()});picker();loadFuel();sync();
})();
